[package]
name = "qr"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15"
imageproc = "0.25.0"
reqwest = { version = "0.12.24", features = ["blocking"] }
serde = "1.0"
serde_json = "1.0"
